name: Tests

on:
  - push
  - pull_request

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Run tests
        run: yarn test

  web-integration:
    name: Web integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
      - name: Run tests
        run: yarn workspace web-example run test

  ios-integration:
    name: iOS integration tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Use CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: examples/vanilla/ios/Podfile.lock
      - name: Install NPM dependencies
        run: yarn --frozen-lockfile --non-interactive --network-timeout 60000
      - name: Install CocoaPods dependencies
        run: pod install --project-directory=examples/vanilla/ios
      - name: Run tests
        run: yarn workspace vanilla-example run test-ios

  types:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
      - name: Check package types
        run: yarn types
      - name: Check web example types
        run: yarn workspace web-example run tsc
      - name: Check vanilla example types
        run: yarn workspace vanilla-example run tsc

  format:
    name: Code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Check formatting
        run: yarn check-format

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Lint flipper plugin
        run: yarn workspace flipper-plugin-performance run lint

  build:
    name: Package builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Build packages
        env:
          PACKAGES: flipper-plugin-performance react-native-performance
        run: for p in $PACKAGES; do pushd packages/$p && npm pack --dry-run && popd; done
